services:
  - type: web
    name: alesky-gym-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/gimnasio-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m"
      - key: SERVER_PORT
        value: "8080"
