name: Debug Secrets Configuration

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [ debug-secrets ]  # Only on debug branch

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check GitHub Token
        run: |
          echo "GitHub Token exists: ${{ secrets.GITHUB_TOKEN != '' }}"
          
      - name: Check Firebase Service Account
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "❌ FIREBASE_SERVICE_ACCOUNT secret is NOT configured"
            echo "🔧 Please add the Firebase service account JSON as a secret named 'FIREBASE_SERVICE_ACCOUNT'"
          else
            echo "✅ FIREBASE_SERVICE_ACCOUNT secret is configured"
            echo "📄 Secret length: $(echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' | wc -c) characters"
          fi
          
      - name: List all repository secrets (names only)
        run: |
          echo "🔍 Checking if secrets are properly configured..."
          echo "Note: This cannot show secret values for security reasons"
          
      - name: Show Firebase project configuration
        run: |
          echo "🔥 Firebase Configuration:"
          echo "Project ID: alesky-gym-rosa"
          echo "Expected hosting path: GestionClases-Frontend/dist/angular/browser"
          
      - name: Verify Firebase config file
        run: |
          echo "📄 Firebase config file contents:"
          cat firebase.json
          
      - name: Next Steps
        run: |
          echo "📋 REQUIRED ACTIONS:"
          echo "1. Go to: https://github.com/ProgramaGerman/UDO-Practicas-y-Proyectos/settings/secrets/actions"
          echo "2. Click 'New repository secret'"
          echo "3. Name: FIREBASE_SERVICE_ACCOUNT"
          echo "4. Value: Paste your complete Firebase service account JSON"
          echo "5. Click 'Add secret'"
          echo ""
          echo "🔧 How to get Firebase service account JSON:"
          echo "1. Go to: https://console.firebase.google.com/project/alesky-gym-rosa/settings/serviceaccounts/adminsdk"
          echo "2. Click 'Generate new private key'"
          echo "3. Download the JSON file"
          echo "4. Copy the ENTIRE JSON content (including { and })"
